AspNetMvc/Models/ErrorViewModel.cs
namespace AspNetMvc.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetMvc/Models/Rating.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetMvc.Models
{
    public class Rating
    {
        [Required]
        public int ID { get; set; }
        [Required]
        [Range(1, 5, ErrorMessage = "Rate must be between 1 to 5!")]
        public int Rate { get; set; }
        [Required]
        [MaxLength(80, ErrorMessage = "Exceeded max length! 80 chars requried")]
        public string Name { get; set; }
        [MaxLength(200, ErrorMessage = "Exceeded max length! 200 chars requried")]
        [Required]
        public string Feedback { get; set; }
        public DateTime DateTime { get; set; }
        public Rating(int id, int rate, string name, string feedback)
        {
            ID = id;
            Rate = rate;
            Name = name;   
            Feedback = feedback;
            DateTime = DateTime.Now;
        }

        public Rating()
        {
            DateTime = DateTime.Now;
        }
    }
}

AspNetMvc/Models/RatingService.cs
using Models;

namespace AspNetMvc.Models {
    public class RatingService : IDataService<Rating, int> {

        private static List<Rating> ratings = new List<Rating>()
        {
            new Rating(1, 5, "dvir", "Awesome website!"),
            new Rating(2, 5, "hadar", "Very good website"),
            new Rating(3, 4, "dan", "I liked this")
        };

        public bool Create(Rating entity)
        {
            try { 
                entity.ID = ratings.Max(r => r.ID) + 1; }
            catch {
                entity.ID = 1;
            }   

            ratings.Add(entity);
            return true;
        }

        public bool Delete(int id)
        {
            var rating = ratings.Find(rating => rating.ID == id);
            if(rating == null) 
                return false;

            ratings.Remove(rating);
            return true;
        }

        public List<Rating> GetAll()
        {
            return ratings;
        }

        public Rating GetById(int id)
        {
            return ratings.Find(rating => rating.ID == id);
        }

        public bool Update(Rating entity)
        {
            var rating = ratings.Find(rating => rating.ID == entity.ID);

            if (rating == null)
                return false;

            rating.Feedback = entity.Feedback;
            rating.Rate = entity.Rate;
            return true;
        }
    }
}

AspNetMvc/Controllers/HomeController.cs
using AspNetMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AspNetMvc.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return Redirect("/Rating/index.html");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AspNetMvc/Controllers/RatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetMvc.Data;
using AspNetMvc.Models;
using Models;

namespace AspNetMvc.Controllers {
    public class RatingsController : Controller {
        private readonly IDataService<Rating, int> service;

        public RatingsController()
        {
            service = new RatingService();
        }

        // GET: Ratings
        public IActionResult Index()
        {
            return View(service.GetAll());
        }

        public IActionResult Search()
        {
            return View("Index", service.GetAll());
        }
        [HttpPost]
        public IActionResult Search(string query)
        {

            if (query == null)
            {
                return View("Index",query);
            }
            else
            {
                var search = service.GetAll().FindAll(Rating => Rating.Feedback.Contains(query));
                return View("Index", search);
            }

        }
        public IActionResult SearchPart(string query)
        {

            if (query == null)
            {
                var all = service.GetAll();
                return PartialView(all);
            }
            else
            {
                var search = service.GetAll().FindAll(Rating => Rating.Feedback.Contains(query));
                if(search.Count == 0)
                {
                    return PartialView(null);
                }
                return PartialView(search);
            }

        }

        // GET: Ratings/Details/5
        public IActionResult Details(int id)
        {
            var rating = service.GetById(id);
            if (rating == null)
            {
                return NotFound();
            }

            return View(rating);
        }

        // GET: Ratings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ratings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ID,Rate,Name,Feedback")] Rating rating)
        {
            if (ModelState.IsValid)
            {
                service.Create(rating);
                return RedirectToAction(nameof(Index));
            }
            return View(rating);
        }

        // GET: Ratings/Edit/5
        public IActionResult Edit(int id)
        {
            var rating = service.GetById(id);
            if (rating == null)
            {
                return NotFound();
            }
            return View(rating);
        }

        // POST: Ratings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("ID,Rate,Name,Feedback")] Rating rating)
        {
            if (id != rating.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    service.Update(rating);
                }
                catch (Exception)
                {
                    if (!RatingExists(rating.ID))
                    {
                        return NotFound();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rating);
        }

        // GET: Ratings/Delete/5
        public IActionResult Delete(int id)
        {
            var rating = service.GetById(id);
            if (rating == null)
            {
                return NotFound();
            }

            return View(rating);
        }

        // POST: Ratings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var rating = service.GetById(id);
            service.Delete(rating.ID);
            return RedirectToAction(nameof(Index));
        }

        private bool RatingExists(int id)
        {
            return service.GetAll().Any(rating => rating.ID == id);
        }
    }
}

AspNetMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AspNetMvc/Views/Ratings/Create.cshtml
@model AspNetMvc.Models.Rating

@{
	ViewData["Title"] = "Create";
}
<img class="logo" src="~/css/webIcon.png" />
<h1>Create</h1>

<h4>Rating</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div class="form-group">
				<fieldset class="rating">
					<input type="radio" id="star5" name="@Html.NameFor(model => model.Rate)" value="5" required />
					<label for="star5" title="WOW!">5 stars</label>
					<input type="radio" id="star4" name="@Html.NameFor(model => model.Rate)" value="4" />
					<label for="star4" title="Pretty good">4 stars</label>
					<input type="radio" id="star3" name="@Html.NameFor(model => model.Rate)" value="3" />
					<label for="star3" title="Cool">3 stars</label>
					<input type="radio" id="star2" name="@Html.NameFor(model => model.Rate)" value="2" />
					<label for="star2" title="Not good">2 stars</label>
					<input type="radio" id="star1" name="@Html.NameFor(model => model.Rate)" value="1" />
					<label for="star1" title="Bad!!">1 star</label>
				</fieldset>
				<br/>
				<span asp-validation-for="Rate" class="text-danger float-rate"></span>
			</div>
			<br />
			<br />
			<div class="form-group">
				<input asp-for="Name" placeholder="Enter Name" class="form-control" style="border-radius: 30px;" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<br />
			<div class="form-group">
				<input asp-for="Feedback" placeholder="Write Feedback" class="form-control" style="border-radius: 30px;" />
				<span asp-validation-for="Feedback" class="text-danger"></span>
			</div>
			<br />
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-primary" /> |
				<button type="button" class="btn btn-secondary" onClick="location.href='@Url.Action("", "Ratings")'">Cancel</button>
			</div>
		</form>
	</div>
</div>


@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

AspNetMvc/Views/Ratings/Delete.cshtml
@model AspNetMvc.Models.Rating

@{
    ViewData["Title"] = "Delete";
}
<img class="logo" src="~/css/webIcon.png" />


<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rate)
        </dt>
        <dd class="col-sm-10">
            @for (int i = 0; i < Model.Rate; i++)
            {
                <span>★</span>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Feedback)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Feedback)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <button type="button" class="btn btn-secondary" onClick="location.href='@Url.Action("", "Ratings")'">Cancel</button>
    </form>
</div>

AspNetMvc/Views/Ratings/Details.cshtml
@model AspNetMvc.Models.Rating

@{
    ViewData["Title"] = "Details";
}
<img class="logo" src="~/css/webIcon.png" />
<h1>Info</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rate)
        </dt>
        <dd class="col-sm-10">
            @for (int i = 0; i < Model.Rate; i++)
            {
                <span>★</span>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Feedback)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Feedback)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateTime)
        </dd>
    </dl>
</div>
<div>
    <button type="button" class="btn btn-primary" onClick="location.href='@Url.Action("Edit", "Ratings")' + '/' + @Model?.ID">Edit</button> |
    <button type="button" class="btn btn-secondary" onClick="location.href='@Url.Action("", "Ratings")'">Cancel</button>

</div>

AspNetMvc/Views/Ratings/Edit.cshtml
@model AspNetMvc.Models.Rating

@{
    ViewData["Title"] = "Edit";
}
<img class="logo" src="~/css/webIcon.png" />
<h1>Edit feedback</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <tr>
                    <td>
                        <fieldset class="rating">
                            <input type="radio" id="star5" name="@Html.NameFor(model => model.Rate)" value="5" required />
                            <label for="star5" title="WOW!">5 stars</label>
                            <input type="radio" id="star4" name="@Html.NameFor(model => model.Rate)" value="4" />
                            <label for="star4" title="Pretty good">4 stars</label>
                            <input type="radio" id="star3" name="@Html.NameFor(model => model.Rate)" value="3" />
                            <label for="star3" title="Cool">3 stars</label>
                            <input type="radio" id="star2" name="@Html.NameFor(model => model.Rate)" value="2" />
                            <label for="star2" title="Not good">2 stars</label>
                            <input type="radio" id="star1" name="@Html.NameFor(model => model.Rate)" value="1" />
                            <label for="star1" title="Bad!!">1 star</label>
                        </fieldset>
                    </td>
                </tr>
            </div>
            <br /><br />
            <div class="form-group">
                <input asp-for="Name" class="form-control" readonly style="border-radius: 30px;" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input asp-for="Feedback" class="form-control" placeholder="Write Feedback" style="border-radius: 30px;"/>
                <span asp-validation-for="Feedback" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" /> |
                <button type="button" class="btn btn-secondary" onClick="location.href='@Url.Action("", "Ratings")'">Cancel</button>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

AspNetMvc/Views/Ratings/Index.cshtml
@model IEnumerable<AspNetMvc.Models.Rating>
@{
    ViewData["Title"] = "Index";
}

<img class="logo" src="~/css/webIcon.png" />


<div>
    <form asp-action="Search" class="search">
        <input name="query" placeholder="Search feedback" id="Search" />
        <input type="submit" value="search" onkeydown="SubmitForm()" />
    </form>
</div>

@{

    if (Model == null)
    {
        <div> No Rating With that Name </div>
    }
    else
    {
        <button type="button" class="btn btn-primary" onClick="location.href='@Url.Action("Create", "Ratings")'">Write a feedback!</button>
        <table class="table">
            <thead>
                <tr>
                <th></th>
                    <th class="table-head">
                        @Html.DisplayNameFor(model => model.Rate)
                    </th>
                    <th class="table-head">
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th class="table-head">
                        @Html.DisplayNameFor(model => model.Feedback)
                    </th>
                    <th class="table-head">
                        Time
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @if (item.Rate < 3)
                            {
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-emoji-frown" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                    <path d="M4.285 12.433a.5.5 0 0 0 .683-.183A3.498 3.498 0 0 1 8 10.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.498 4.498 0 0 0 8 9.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" />
                                </svg>
                            }
                            else
                            {
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-emoji-smile" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                    <path d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" />
                                </svg>
                            }
                        </td>
                        <td>
                            @for (int i = 0; i < item.Rate; i++)
                            {
                                <span class="fa fa-star checked"></span>
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="feedback">
                            @Html.DisplayFor(modelItem => item.Feedback)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateTime)
                        </td>

                        <td>
                            <span class="Edit">
                                <button type="button" class="btn btn-primary" onClick="location.href='@Url.Action("Edit", "Ratings")' + '/' + @item.ID">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"></path>
                                    </svg>
                                </button>|
                            </span>

                            <span class="Details">
                                <button type="button" class="btn btn-primary" onClick="location.href='@Url.Action("Details", "Ratings")' + '/' + @item.ID">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                                        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"></path>
                                    </svg>
                                </button>|
                            </span>

                            <span class="Delete">
                                <button type="button" class="btn btn-primary" onClick="location.href='@Url.Action("Delete", "Ratings")' + '/' + @item.ID">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                    </svg>
                                </button>
                            </span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

@{
    try
    {
        double avg = Math.Round(Model.Average(r => r.Rate), 2);
        string width = (avg * 100 / 5).ToString() + "%";
        <div class="star-ratings">
            <div class="fill-ratings" style="width:@width">
                <span class="stars">★★★★★</span>
            </div>
            <div class="empty-ratings">
                <span class="stars">★★★★★</span>
            </div>
        </div>
    }
    catch { }
}
<span><a asp-action="index"> GoBack To Full List</a></span>




@section Scripts{
<script src="~/js/Search.js"> </script>
<script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
<script src="~/js/site.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    }

AspNetMvc/Views/Ratings/SearchPart.cshtml
@model IEnumerable<AspNetMvc.Models.Rating>

@{
    ViewData["Title"] = "Index";
}


@{
    if (Model == null)
    {
        <div> No Rating With that Review </div>

    }
    else
    {

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (item.Rate < 3)
                    {
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-emoji-frown" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path d="M4.285 12.433a.5.5 0 0 0 .683-.183A3.498 3.498 0 0 1 8 10.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.498 4.498 0 0 0 8 9.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" />
                        </svg>
                    }
                    else
                    {
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-emoji-smile" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" />
                        </svg>
                    }
                </td>
                <td>
                    @for (int i = 0; i < item.Rate; i++)
                    {
                        <span class="fa fa-star checked"></span>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Feedback)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTime)
                </td>
                <td>
                    <span class="Edit">
                        <button type="button" class="btn btn-primary" onClick="location.href='@Url.Action("Edit", "Ratings")' + '/' + @item.ID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"></path>
                            </svg>
                        </button>|
                    </span>

                    <span class="Details">
                        <button type="button" class="btn btn-primary" onClick="location.href='@Url.Action("Details", "Ratings")' + '/' + @item.ID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"></path>
                            </svg>
                        </button>|
                    </span>

                    <span class="Delete">
                        <button type="button" class="btn btn-primary" onClick="location.href='@Url.Action("Delete", "Ratings")' + '/' + @item.ID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                            </svg>
                        </button>
                    </span>
                </td>
            </tr>
        }


    }

}